### ISSUE TITLE
cant change between players through toggle

### ISSUE THREAD

**Issue by sonofadra90n** [FeralCompany/FeralMinimap#4]

**Comment by FerusGrim** [comment]
Interesting. I'm not sure what I would have touched in my last update that would cause this issue. Gimme a bit to look into it.

**Comment by FerusGrim** [comment]
I believe this is closed by https://github.com/FeralCompany/FeralMinimap/commit/5294687f546c942c9fb03fac754c607225539f6a. I will re-open this issue if you're still having trouble, but I was able to switch between targets in-game without issue.
